[toolchain]
anchor_version = "1.0.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow = "794nTFNyJknzDrR13ApSfVyNCRvcvnCN3BVDfic8dcZD"

[programs.localnet]
escrow = "EscrowXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/blitz-dev.json"

[scripts]
test = "cargo test"

[hooks]

