const DEMO_TRACE = [
  {
    delay: 0,
    icon: "🧠",
    section: "Planning",
    lines: [
      "Consumer agent analysing brief...",
      "→ Identified 4 specialist calls needed",
      "→ UX copy, hero copy, research, strategy",
    ],
  },
  {
    delay: 1200,
    icon: "🔍",
    section: "Agent Discovery",
    lines: [
      "Querying index API...",
      "→ 6 agents found matching criteria",
      "→ Selected primary: ollama-copy ⭐ 4.8 · 0.0008 SOL",
      "→ Selected judge: ollama-strategy ⭐ 94% accuracy · 0.0004 SOL",
    ],
  },
  {
    delay: 2800,
    icon: "💸",
    section: "Escrow Deposit",
    lines: [
      "Locking 0.0012 SOL in escrow...",
      "→ TX: 5xWmNT4E...w24f [EXPLORER:5xWmNT4Ew24f]",
      "→ Escrow PDA: Gx7kBL4v...",
      "✅ Funds locked",
    ],
  },
  {
    delay: 4500,
    icon: "🤖",
    section: "Primary Agent Responding",
    lines: [
      "POST https://abc123.ngrok-free.app/answer",
      "← HTTP 402 Payment Required",
      "→ Verifying escrow on-chain...",
      "✅ Payment confirmed · Delivering response...",
    ],
  },
  {
    delay: 7000,
    icon: "⚖️",
    section: "Attestation Scoring",
    lines: [
      "ollama-strategy evaluating output...",
      "→ accuracy:      4.8 / 5",
      "→ completeness:  4.5 / 5",
      "→ relevance:     5.0 / 5",
      "→ format:        4.6 / 5",
      "→ latency:       4.9 / 5",
      "→ weighted avg:  4.76 / 5",
    ],
  },
  {
    delay: 9000,
    icon: "🔐",
    section: "Commit-Reveal",
    lines: [
      "Consumer commit: 0xa3f2...8b1c",
      "Specialist commit: 0xb81c...3f90",
      "Consumer reveals: score 5 ✅",
      "Specialist reveals: score 4 ✅",
      "→ TX: 9mKpCsaX...3q [EXPLORER:9mKpCsaX3q]",
      "→ EscrowState closed · rent returned to consumer",
    ],
  },
  {
    delay: 10500,
    icon: "✅",
    section: "Complete",
    lines: [
      "4 agents · 12 transactions · 0.0046 SOL total",
      "Quality score: 4.76 / 5",
      "View all transactions on Solana Explorer ↗",
    ],
  },
];

const DEMO_OUTPUT = `<!DOCTYPE html>
<html>
<head><style>
  body { font-family: system-ui; background: #0a0a0a; color: #fff; margin: 0; padding: 40px; }
  .hero { max-width: 800px; margin: 0 auto; text-align: center; padding: 80px 20px; }
  h1 { font-size: 3rem; font-weight: 800; background: linear-gradient(135deg, #9945FF, #14F195); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
  .sub { color: #888; font-size: 1.2rem; margin: 20px 0 40px; }
  .cta { background: linear-gradient(135deg, #9945FF, #14F195); border: none; padding: 16px 40px; border-radius: 8px; color: #000; font-weight: 700; font-size: 1rem; cursor: pointer; }
</style></head>
<body>
  <div class="hero">
    <h1>[PRODUCT NAME]</h1>
    <p class="sub">Generated by the Reddi Agent Protocol · 4 specialists · 12 on-chain transactions</p>
    <button class="cta">Get Started →</button>
  </div>
</body>
</html>`;

export async function POST(req: Request) {
  const { brief } = await req.json();

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      for (const step of DEMO_TRACE) {
        await new Promise((r) => setTimeout(r, step.delay));
        controller.enqueue(encoder.encode(`data: ${JSON.stringify(step)}\n\n`));
      }
      // Final: send the generated HTML
      const productName = (brief as string)
        .trim()
        .split(/\s+/)
        .slice(0, 3)
        .join(" ");
      const html = DEMO_OUTPUT.replace("[PRODUCT NAME]", productName || "Your Product");
      controller.enqueue(
        encoder.encode(`data: ${JSON.stringify({ type: "html", content: html })}\n\n`)
      );
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
    },
  });
}
