export type AgentRole = "specialist" | "attestor" | "consumer";

export type FeatureEntry = {
  id: string;
  bucket: string;
  title: string;
  summary: string;
  roles: AgentRole[];
  evidence: string[];
};

export const FEATURE_CATALOG: FeatureEntry[] = [
  {
    id: "A1-consent-runtime-gates",
    bucket: "A",
    title: "Onboarding step gates for consent + runtime readiness",
    summary: "Consent checkboxes and runtime readiness gates block unsafe onboarding progression before registration.",
    roles: ["specialist"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature", "e2e/onboarding.spec.ts"],
  },
  {
    id: "A1-wallet-sponsorship",
    bucket: "A",
    title: "Wallet + sponsorship readiness constraints",
    summary: "Supports existing and bootstrap wallet paths with backup checkpoints and onboarding-safe sponsorship constraints.",
    roles: ["specialist"],
    evidence: ["app/api/onboarding/wallet/route.ts", "lib/onboarding/wallet-sponsorship.ts"],
  },
  {
    id: "A1-register-onchain",
    bucket: "A",
    title: "On-chain register flow with explorer proof",
    summary: "Step 5 registration submits on-chain and returns transaction signature + explorer proof in integration environments.",
    roles: ["specialist"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature", "artifacts/integration-lane/"],
  },
  {
    id: "A2-healthcheck-attestation-gate",
    bucket: "A",
    title: "Healthcheck-gated attestation eligibility",
    summary: "Attestation is blocked until endpoint healthcheck passes.",
    roles: ["attestor", "specialist"],
    evidence: ["app/api/onboarding/healthcheck/route.ts", "app/api/onboarding/attestation/route.ts"],
  },
  {
    id: "A2-onchain-attestation-submit",
    bucket: "A",
    title: "On-chain attestation submit path",
    summary: "Attestors submit on-chain evaluation metadata with persisted audit records.",
    roles: ["attestor"],
    evidence: ["app/api/onboarding/attestation/route.ts", "app/api/onboarding/audit/route.ts"],
  },
  {
    id: "A2-attestation-audit-persistence",
    bucket: "A",
    title: "Attestation + onboarding audit persistence",
    summary: "Audit records are stored and queryable for verification.",
    roles: ["attestor", "consumer"],
    evidence: ["app/api/onboarding/audit/route.ts"],
  },
  {
    id: "A2-operator-key-recovery",
    bucket: "A",
    title: "Operator-key status and recovery signals",
    summary: "Missing or malformed operator signer states fail explicitly with recovery guidance.",
    roles: ["attestor"],
    evidence: ["lib/__tests__/operator-key-rotation.test.ts", "lib/__tests__/onboarding-operator-status-routes.test.ts"],
  },
  {
    id: "A2-confirm-dispute-followthrough",
    bucket: "A",
    title: "Post-attestation confirm/dispute flow",
    summary: "Settlement actions remain available and state-consistent after attestation.",
    roles: ["consumer", "attestor"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature"],
  },
  {
    id: "B-tag-filter",
    bucket: "B",
    title: "Capability/tag discovery filters",
    summary: "Registry supports tag-based discovery (single and CSV filters).",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-attested-health-filter",
    bucket: "B",
    title: "Attestation + health filtering",
    summary: "Consumers can restrict discovery to attested and healthy specialists.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-deterministic-ranking",
    bucket: "B",
    title: "Deterministic ranking tie-breakers",
    summary: "Ranking order uses score -> freshness -> per-call cost for stable selection.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-default-ordering",
    bucket: "B",
    title: "Stable default discovery ordering",
    summary: "Default ordering remains attested-first, then health, then feedback.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-bridge-sort.test.ts"],
  },
  {
    id: "C-policy-resolve",
    bucket: "C",
    title: "Policy-safe deterministic specialist resolve",
    summary: "Planner resolve enforces policy constraints and emits explicit selection reasons.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-resolve-route.test.ts"],
  },
  {
    id: "C-invoke-guardrails",
    bucket: "C",
    title: "Paid invoke with policy + budget guardrails",
    summary: "Planner invoke enforces budget and policy checks with auditable run traces.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts"],
  },
  {
    id: "C-quality-signal-routing",
    bucket: "C",
    title: "Quality signals influence routing and reputation",
    summary: "Post-call scoring persists and updates specialist routing signals with commit triggers.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "C-reputation-event-path",
    bucket: "C",
    title: "Reputation event pipeline contracts",
    summary: "Event-producing paths for planner lifecycle remain test-backed.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/torque-event-route.test.ts", "lib/__tests__/torque-client.test.ts"],
  },
  {
    id: "D-x402-public-bypass",
    bucket: "D/E",
    title: "x402 public-path compatibility with token-gated control routes",
    summary: "Payment handshake routes remain public while control paths stay protected.",
    roles: ["specialist", "consumer"],
    evidence: ["lib/__tests__/endpoint-security-compat.test.ts"],
  },
  {
    id: "E-operator-rotation",
    bucket: "D/E",
    title: "Operator-key rotation safeguards",
    summary: "Missing/invalid keys surface actionable readiness and rotation guidance.",
    roles: ["attestor"],
    evidence: ["lib/__tests__/operator-key-rotation.test.ts", "lib/__tests__/onboarding-operator-status-routes.test.ts"],
  },
  {
    id: "E-rpc-override-fallback",
    bucket: "D/E",
    title: "RPC override and fallback contracts",
    summary: "Explicit RPC override wins; devnet fallback is enforced when absent.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/program-rpc-config.test.ts"],
  },
  {
    id: "E-integration-lane-evidence",
    bucket: "D/E",
    title: "Runtime-backed integration evidence lane",
    summary: "Integration-lane produces artifact packs with readiness telemetry.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["artifacts/integration-lane/", "scripts/run-integration-lane.sh"],
  },
  {
    id: "F-auto-swap-guardrails",
    bucket: "F",
    title: "Cross-token auto-swap settlement guardrails",
    summary: "Token mismatch triggers swap path when configured; missing swap client fails fast.",
    roles: ["consumer", "specialist"],
    evidence: ["docs/bdd/features/bucket-f-jupiter-settlement.feature", "packages/x402-solana/tests/payment.test.ts"],
  },
  {
    id: "F-jupiter-bootstrap",
    bucket: "F",
    title: "Jupiter client bootstrap by API-key policy",
    summary: "Jupiter client returns null when key is absent and singleton when configured.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/jupiter-client.test.ts"],
  },
  {
    id: "F-invoke-swap-wiring",
    bucket: "F",
    title: "Planner invoke wiring for swap client",
    summary: "Invoke route keeps swap-aware settlement wiring connected.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts"],
  },
  {
    id: "G-torque-safe-modes",
    bucket: "G",
    title: "Torque client safe modes",
    summary: "Telemetry client safely handles enabled, disabled, and network-failure paths.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-client.test.ts"],
  },
  {
    id: "G-torque-event-validation",
    bucket: "G",
    title: "Event route validation for retention payloads",
    summary: "Onboarding/planner/reputation events are validated and accepted with stable contracts.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-event-route.test.ts", "lib/__tests__/torque-onboarding-event.test.ts"],
  },
  {
    id: "G-leaderboard-safe-ui",
    bucket: "G",
    title: "Leaderboard API/UI resilience",
    summary: "Leaderboard handles empty/live states gracefully and avoids sensitive token exposure.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-leaderboard-route.test.ts", "e2e/leaderboard.spec.ts"],
  },
  {
    id: "H-register-consumer-idempotent",
    bucket: "H",
    title: "Consumer registration with idempotent updates",
    summary: "Consumer profiles accept valid wallets, reject invalid ones, and update idempotently.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-register-consumer-route.test.ts"],
  },
  {
    id: "H-tools-manifest",
    bucket: "H",
    title: "Planner tools manifest for orchestrators",
    summary: "Consumer orchestration endpoints are exposed through a manifest contract.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-tools-manifest-route.test.ts"],
  },
  {
    id: "H-resolve-specialist",
    bucket: "H",
    title: "Specialist resolve with reasons",
    summary: "Resolve route returns deterministic candidates with transparent selection reasons.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-resolve-route.test.ts"],
  },
  {
    id: "H-resolve-attestor",
    bucket: "H",
    title: "Attestor resolve success and no-candidate handling",
    summary: "Resolve-attestor supports both positive and explicit no-candidate paths.",
    roles: ["consumer", "attestor"],
    evidence: ["lib/__tests__/planner-resolve-attestor-route.test.ts"],
  },
  {
    id: "H-invoke-settlement-lifecycle",
    bucket: "H",
    title: "Invoke + settlement lifecycle guards",
    summary: "Paid runs transition through release/dispute states; invalid transitions are rejected.",
    roles: ["consumer", "specialist", "attestor"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts", "lib/__tests__/planner-release-route.test.ts"],
  },
  {
    id: "H-quality-signal-linkage",
    bucket: "H",
    title: "Run-linked quality signal persistence",
    summary: "Signals persist against run lifecycle and trigger reputation contracts appropriately.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "H-auditability-split-tracks",
    bucket: "H",
    title: "Independent auditability for settlement and rating",
    summary: "Settlement decisions and quality ratings remain independently queryable.",
    roles: ["consumer", "attestor"],
    evidence: ["lib/__tests__/planner-auditability.test.ts"],
  },
  {
    id: "H-dogfood-escrow-gating",
    bucket: "H",
    title: "Dogfood ping/haiku escrow gate",
    summary: "Escrow release/refund is gated by attestor verification over specialist output quality.",
    roles: ["consumer", "specialist", "attestor"],
    evidence: [
      "lib/__tests__/dogfood-testing-specialist-route.test.ts",
      "lib/__tests__/dogfood-testing-attestor-route.test.ts",
      "lib/__tests__/dogfood-consumer-run-route.test.ts",
    ],
  },
  {
    id: "H-dogfood-ui-outcomes",
    bucket: "H",
    title: "Dogfood UI pass/fail settlement visibility",
    summary: "UI explicitly surfaces both released and refunded outcomes.",
    roles: ["consumer"],
    evidence: ["e2e/dogfood.spec.ts"],
  },
  {
    id: "OO-specialist-happy",
    bucket: "OpenOnion",
    title: "OpenOnion specialist onboarding happy path",
    summary: "ConnectOnion specialist adapters register and appear in marketplace with health status.",
    roles: ["specialist"],
    evidence: ["projects/reddi-agent-protocol/features/openonion-onboarding.feature", "docs/integrations/openonion/OPENONION-ADAPTER-CONTRACT.md"],
  },
  {
    id: "OO-specialist-unpaid-reject",
    bucket: "OpenOnion",
    title: "OpenOnion unpaid invocation rejection",
    summary: "Specialist adapter enforces payment-required semantics and prevents side effects.",
    roles: ["specialist", "consumer"],
    evidence: ["lib/integrations/openonion/specialist/adapter.ts", "lib/__tests__/openonion-specialist-adapter.test.ts"],
  },
  {
    id: "OO-specialist-contract-mismatch",
    bucket: "OpenOnion",
    title: "OpenOnion endpoint contract mismatch guard",
    summary: "Registration preflight blocks incompatible adapter contracts with remediation guidance.",
    roles: ["specialist"],
    evidence: ["app/api/register/probe/route.ts", "lib/__tests__/register-probe-route.test.ts"],
  },
  {
    id: "OO-attestor-happy",
    bucket: "OpenOnion",
    title: "OpenOnion attestor schema path",
    summary: "Attestor payloads follow fixed rubric schema and integrate with settlement flow.",
    roles: ["attestor"],
    evidence: ["lib/integrations/openonion/attestor/schema.ts", "lib/__tests__/openonion-attestor-schema.test.ts"],
  },
  {
    id: "OO-attestor-schema-drift",
    bucket: "OpenOnion",
    title: "OpenOnion schema drift rejection",
    summary: "Missing rubric dimensions trigger deterministic validation failures.",
    roles: ["attestor"],
    evidence: ["app/api/planner/tools/signal/route.ts", "lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "OO-consumer-happy",
    bucket: "OpenOnion",
    title: "OpenOnion consumer orchestration path",
    summary: "Consumer plugin executes discover -> resolve -> invoke -> monitor flow.",
    roles: ["consumer"],
    evidence: ["lib/integrations/openonion/consumer/orchestrator.ts", "app/api/planner/tools/invoke/route.ts"],
  },
  {
    id: "OO-consumer-failover",
    bucket: "OpenOnion",
    title: "OpenOnion unreachable-specialist failover",
    summary: "Retry-exhausted runs return refund disposition with explicit failure reason.",
    roles: ["consumer"],
    evidence: ["lib/integrations/openonion/consumer/orchestrator.ts", "lib/__tests__/openonion-consumer-orchestrator.test.ts"],
  },
  {
    id: "OO-hosted-network-safety",
    bucket: "OpenOnion",
    title: "Hosted localhost/private-network guard",
    summary: "Hosted endpoint validation blocks unsafe localhost/private target callbacks.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/integrations/openonion/network-policy.ts", "app/api/register/probe/route.ts"],
  },
];

