export type AgentRole = "specialist" | "attestor" | "consumer";

export type FeatureEntry = {
  id: string;
  bucket: string;
  title: string;
  summary: string;
  roles: AgentRole[];
  evidence: string[];
};

export const FEATURE_CATALOG: FeatureEntry[] = [
  {
    id: "A1-consent-runtime-gates",
    bucket: "A",
    title: "Guided onboarding that prevents bad setup",
    summary: "New specialists only move forward when consent and runtime checks are complete, so they avoid common setup mistakes.",
    roles: ["specialist"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature", "e2e/onboarding.spec.ts"],
  },
  {
    id: "A1-wallet-sponsorship",
    bucket: "A",
    title: "Flexible wallet onboarding with safety rails",
    summary: "Operators can use an existing wallet or bootstrap a new one, with backup checkpoints and safe sponsorship limits.",
    roles: ["specialist"],
    evidence: ["app/api/onboarding/wallet/route.ts", "lib/onboarding/wallet-sponsorship.ts"],
  },
  {
    id: "A1-register-onchain",
    bucket: "A",
    title: "One flow to register and prove it on-chain",
    summary: "Registration completes with a real transaction signature and explorer proof, ready to show in demos and audits.",
    roles: ["specialist"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature", "artifacts/integration-lane/"],
  },
  {
    id: "A2-healthcheck-attestation-gate",
    bucket: "A",
    title: "Attestation only starts when health checks pass",
    summary: "The platform blocks attestation until endpoint health is good, reducing noisy or invalid evaluations.",
    roles: ["attestor", "specialist"],
    evidence: ["app/api/onboarding/healthcheck/route.ts", "app/api/onboarding/attestation/route.ts"],
  },
  {
    id: "A2-onchain-attestation-submit",
    bucket: "A",
    title: "Attestors can publish verifiable on-chain evaluations",
    summary: "Attestation results are submitted with chain-linked metadata, giving both teams and users a verifiable quality trail.",
    roles: ["attestor"],
    evidence: ["app/api/onboarding/attestation/route.ts", "app/api/onboarding/audit/route.ts"],
  },
  {
    id: "A2-attestation-audit-persistence",
    bucket: "A",
    title: "Persistent audit history for onboarding and attestation",
    summary: "Evaluation and onboarding events are stored so operators can review what happened later, not just live.",
    roles: ["attestor", "consumer"],
    evidence: ["app/api/onboarding/audit/route.ts"],
  },
  {
    id: "A2-operator-key-recovery",
    bucket: "A",
    title: "Clear operator key readiness and recovery guidance",
    summary: "If the signing key is missing or invalid, the app shows explicit recovery steps instead of silent failures.",
    roles: ["attestor"],
    evidence: ["lib/__tests__/operator-key-rotation.test.ts", "lib/__tests__/onboarding-operator-status-routes.test.ts"],
  },
  {
    id: "A2-confirm-dispute-followthrough",
    bucket: "A",
    title: "Post-evaluation settlement actions stay available",
    summary: "After evaluation, teams can still confirm or dispute outcomes with consistent state behavior.",
    roles: ["consumer", "attestor"],
    evidence: ["docs/bdd/features/bucket-a-onboarding.feature"],
  },
  {
    id: "B-tag-filter",
    bucket: "B",
    title: "Find agents by capability tags",
    summary: "Consumers can quickly filter the marketplace using tags that match their use case.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-attested-health-filter",
    bucket: "B",
    title: "Filter by trust and runtime health",
    summary: "Discovery can be restricted to specialists that are both attested and currently healthy.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-deterministic-ranking",
    bucket: "B",
    title: "Stable ranking that avoids random ordering",
    summary: "Candidates are ranked consistently using quality, freshness, and cost signals.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-route.test.ts"],
  },
  {
    id: "B-default-ordering",
    bucket: "B",
    title: "Reliable default marketplace sort",
    summary: "Even without custom sorting, results remain in a predictable order focused on trust and reliability.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/registry-bridge-sort.test.ts"],
  },
  {
    id: "C-policy-resolve",
    bucket: "C",
    title: "Policy-aware matching before hiring",
    summary: "Planner resolution respects policy constraints and explains why a candidate was chosen.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-resolve-route.test.ts"],
  },
  {
    id: "C-invoke-guardrails",
    bucket: "C",
    title: "Safe paid invocation with budget controls",
    summary: "Consumer calls run through budget and policy checks before execution, with traceable run records.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts"],
  },
  {
    id: "C-quality-signal-routing",
    bucket: "C",
    title: "Quality feedback that improves future routing",
    summary: "Post-run scoring is saved and fed back into specialist selection and reputation updates.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "C-reputation-event-path",
    bucket: "C",
    title: "End-to-end reputation event pipeline",
    summary: "Planner lifecycle events are captured in a stable pipeline so reputation logic stays consistent.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/torque-event-route.test.ts", "lib/__tests__/torque-client.test.ts"],
  },
  {
    id: "D-x402-public-bypass",
    bucket: "D/E",
    title: "Payment handshake remains open while control paths stay protected",
    summary: "Public payment routes work as expected, while sensitive control routes remain gated.",
    roles: ["specialist", "consumer"],
    evidence: ["lib/__tests__/endpoint-security-compat.test.ts"],
  },
  {
    id: "E-operator-rotation",
    bucket: "D/E",
    title: "Operator key lifecycle safeguards",
    summary: "Teams get explicit readiness checks and safe key-rotation behavior for attestation operations.",
    roles: ["attestor"],
    evidence: ["lib/__tests__/operator-key-rotation.test.ts", "lib/__tests__/onboarding-operator-status-routes.test.ts"],
  },
  {
    id: "E-rpc-override-fallback",
    bucket: "D/E",
    title: "Resilient RPC configuration",
    summary: "Custom RPC settings are honored, and safe fallback behavior is enforced when they are absent.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/program-rpc-config.test.ts"],
  },
  {
    id: "E-integration-lane-evidence",
    bucket: "D/E",
    title: "Integration evidence packs for confidence checks",
    summary: "The integration lane produces reusable proof artifacts and readiness telemetry for release confidence.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["artifacts/integration-lane/", "scripts/run-integration-lane.sh"],
  },
  {
    id: "F-auto-swap-guardrails",
    bucket: "F",
    title: "Cross-token settlement with auto-swap protection",
    summary: "When payer and payee tokens differ, swap-aware handling keeps settlement practical and safe.",
    roles: ["consumer", "specialist"],
    evidence: ["docs/bdd/features/bucket-f-jupiter-settlement.feature", "packages/x402-solana/tests/payment.test.ts"],
  },
  {
    id: "F-jupiter-bootstrap",
    bucket: "F",
    title: "Jupiter integration that fails safely",
    summary: "Swap features enable only when configuration is present, avoiding hidden partial setup states.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/jupiter-client.test.ts"],
  },
  {
    id: "F-invoke-swap-wiring",
    bucket: "F",
    title: "Planner and settlement swap wiring",
    summary: "Swap-aware payment flow is wired directly into invoke so cross-token paths are first-class.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts"],
  },
  {
    id: "G-torque-safe-modes",
    bucket: "G",
    title: "Telemetry that does not break core flows",
    summary: "Retention telemetry works in enabled mode and degrades safely when unavailable.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-client.test.ts"],
  },
  {
    id: "G-torque-event-validation",
    bucket: "G",
    title: "Validated event contracts across onboarding and planner",
    summary: "Event payloads are validated so growth and retention analytics stay consistent.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-event-route.test.ts", "lib/__tests__/torque-onboarding-event.test.ts"],
  },
  {
    id: "G-leaderboard-safe-ui",
    bucket: "G",
    title: "Leaderboard experience for live and empty states",
    summary: "Leaderboard views remain stable whether data is full, empty, or partially available.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/__tests__/torque-leaderboard-route.test.ts", "e2e/leaderboard.spec.ts"],
  },
  {
    id: "H-register-consumer-idempotent",
    bucket: "H",
    title: "Simple consumer registration with safe updates",
    summary: "Consumers can register once and update profiles without duplicate-state issues.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-register-consumer-route.test.ts"],
  },
  {
    id: "H-tools-manifest",
    bucket: "H",
    title: "Orchestrator-ready tools manifest",
    summary: "Consumer automation surfaces are exposed in a clear manifest for agent frameworks.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-tools-manifest-route.test.ts"],
  },
  {
    id: "H-resolve-specialist",
    bucket: "H",
    title: "Transparent specialist selection",
    summary: "Resolve returns clear candidate reasoning so consumers can trust routing decisions.",
    roles: ["consumer"],
    evidence: ["lib/__tests__/planner-resolve-route.test.ts"],
  },
  {
    id: "H-resolve-attestor",
    bucket: "H",
    title: "Attestor selection with explicit fallback behavior",
    summary: "Consumers can select judges confidently and get clear feedback when none are eligible.",
    roles: ["consumer", "attestor"],
    evidence: ["lib/__tests__/planner-resolve-attestor-route.test.ts"],
  },
  {
    id: "H-invoke-settlement-lifecycle",
    bucket: "H",
    title: "Full invoke-to-settlement lifecycle controls",
    summary: "Runs progress through release/dispute paths with enforced state rules and payment guardrails.",
    roles: ["consumer", "specialist", "attestor"],
    evidence: ["lib/__tests__/planner-invoke-route.test.ts", "lib/__tests__/planner-release-route.test.ts"],
  },
  {
    id: "H-quality-signal-linkage",
    bucket: "H",
    title: "Quality scoring linked to run outcomes",
    summary: "Consumer feedback stays connected to the right run and informs reputation logic.",
    roles: ["consumer", "specialist"],
    evidence: ["lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "H-auditability-split-tracks",
    bucket: "H",
    title: "Independent audit tracks for settlement and scoring",
    summary: "Teams can audit money movement and quality scoring separately without losing traceability.",
    roles: ["consumer", "attestor"],
    evidence: ["lib/__tests__/planner-auditability.test.ts"],
  },
  {
    id: "H-dogfood-escrow-gating",
    bucket: "H",
    title: "Quality-gated escrow outcomes in dogfood flow",
    summary: "Escrow release vs refund is determined by attested output quality, not just task completion claims.",
    roles: ["consumer", "specialist", "attestor"],
    evidence: [
      "lib/__tests__/dogfood-testing-specialist-route.test.ts",
      "lib/__tests__/dogfood-testing-attestor-route.test.ts",
      "lib/__tests__/dogfood-consumer-run-route.test.ts",
    ],
  },
  {
    id: "H-dogfood-ui-outcomes",
    bucket: "H",
    title: "Visible pass/fail settlement outcomes in UI",
    summary: "Operators can clearly show released and refunded paths during demos.",
    roles: ["consumer"],
    evidence: ["e2e/dogfood.spec.ts"],
  },
  {
    id: "OO-specialist-happy",
    bucket: "OpenOnion",
    title: "OpenOnion specialist onboarding support",
    summary: "ConnectOnion specialists can onboard and become discoverable in the marketplace.",
    roles: ["specialist"],
    evidence: ["projects/reddi-agent-protocol/features/openonion-onboarding.feature", "docs/integrations/openonion/OPENONION-ADAPTER-CONTRACT.md"],
  },
  {
    id: "OO-specialist-unpaid-reject",
    bucket: "OpenOnion",
    title: "OpenOnion payment-required enforcement",
    summary: "Unpaid calls are rejected before work executes, protecting specialist compute and settlement integrity.",
    roles: ["specialist", "consumer"],
    evidence: ["lib/integrations/openonion/specialist/adapter.ts", "lib/__tests__/openonion-specialist-adapter.test.ts"],
  },
  {
    id: "OO-specialist-contract-mismatch",
    bucket: "OpenOnion",
    title: "OpenOnion contract compatibility checks",
    summary: "Registration preflight catches integration mismatches early and gives corrective guidance.",
    roles: ["specialist"],
    evidence: ["app/api/register/probe/route.ts", "lib/__tests__/register-probe-route.test.ts"],
  },
  {
    id: "OO-attestor-happy",
    bucket: "OpenOnion",
    title: "OpenOnion attestor schema integration",
    summary: "Attestor payloads follow a fixed rubric format for predictable evaluation behavior.",
    roles: ["attestor"],
    evidence: ["lib/integrations/openonion/attestor/schema.ts", "lib/__tests__/openonion-attestor-schema.test.ts"],
  },
  {
    id: "OO-attestor-schema-drift",
    bucket: "OpenOnion",
    title: "OpenOnion schema drift protection",
    summary: "Malformed or incomplete attestor payloads are rejected deterministically.",
    roles: ["attestor"],
    evidence: ["app/api/planner/tools/signal/route.ts", "lib/__tests__/planner-signal-route.test.ts"],
  },
  {
    id: "OO-consumer-happy",
    bucket: "OpenOnion",
    title: "OpenOnion consumer orchestration path",
    summary: "OpenOnion consumers can run discover, resolve, invoke, and monitor in one integrated flow.",
    roles: ["consumer"],
    evidence: ["lib/integrations/openonion/consumer/orchestrator.ts", "app/api/planner/tools/invoke/route.ts"],
  },
  {
    id: "OO-consumer-failover",
    bucket: "OpenOnion",
    title: "OpenOnion failover with safe refund behavior",
    summary: "If a specialist becomes unreachable after retries, the run exits with explicit refund disposition.",
    roles: ["consumer"],
    evidence: ["lib/integrations/openonion/consumer/orchestrator.ts", "lib/__tests__/openonion-consumer-orchestrator.test.ts"],
  },
  {
    id: "OO-hosted-network-safety",
    bucket: "OpenOnion",
    title: "Hosted network safety guardrails",
    summary: "Unsafe localhost and private-network callback targets are blocked in hosted contexts.",
    roles: ["specialist", "attestor", "consumer"],
    evidence: ["lib/integrations/openonion/network-policy.ts", "app/api/register/probe/route.ts"],
  },
];
